-- VisionWorks — database-side UUID defaults
--
-- THE BUG THIS FIXES
--
-- Every `id` in this schema is declared `@default(uuid())` in Prisma. That
-- default is generated by the PRISMA CLIENT, in JavaScript, at query time — it
-- is not a column default in Postgres. `prisma migrate` therefore created these
-- columns as plain `uuid NOT NULL` with no DEFAULT at all.
--
-- That is invisible for as long as every write goes through Prisma. It stops
-- being invisible the moment a write goes through PostgREST — which is exactly
-- what a Supabase Server Action does:
--
--   supabase.from('memberships').insert({ orgId, role, status, ... })
--     -> ERROR: null value in column "id" of relation "memberships"
--               violates not-null constraint
--
-- Measured against the live database, not inferred. It broke three real code
-- paths: creating an invitation, writing an audit row, and adding a camera
-- during onboarding.
--
-- This is the same trap as `updatedAt`, which Prisma's `@updatedAt` also
-- maintains client-side. `updatedAt` is handled by the application (it is a
-- meaningful value the app should set deliberately), but a primary key is not
-- something application code should be inventing on every insert — one missed
-- call site is a 500 in production. So the default belongs in the database,
-- where it covers every current and future writer.
--
-- WHY THIS IS SAFE WITH PRISMA
--
-- A column DEFAULT only applies when the INSERT omits the column. Prisma keeps
-- supplying its own client-generated uuid, so Prisma-issued inserts are
-- completely unaffected — the default is a fallback for writers that do not.
-- Both produce a v4 UUID; there is no format difference to reconcile.
--
-- `gen_random_uuid()` is built into Postgres 13+ and is already used throughout
-- 002_auth_triggers.sql, so no extension is required.
--
-- Idempotent: ALTER COLUMN SET DEFAULT is a no-op when the default already
-- matches, so this file is safe to re-run.
--
-- Apply AFTER 007_operator_revoke.sql.

-- Every table whose id is a `@default(uuid())` primary key. Listed explicitly
-- rather than discovered by a catalogue query, so applying this file is a
-- reviewable statement of intent rather than a loop that might catch something
-- unintended.
ALTER TABLE public.organisations      ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.memberships        ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.sites              ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.cameras            ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.zones              ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.zone_minute_stats  ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.zone_day_stats     ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.analysis_sessions  ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.alert_rules        ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.alerts             ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.reports            ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.audit_logs         ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.platform_audit_logs ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- NOT included, deliberately:
--
--   profiles.id         IS the auth.users uuid. It must never be generated —
--                       a default here would silently create a profile with an
--                       id that matches no auth user.
--   platform_admins.profileId  same reasoning; it is a foreign key, not a
--                       generated identity.
